<?php
/**
 * 后台主页
 *
 * @author: xieyong <qxieyongp@163.com>
 * @Date: 2017/8/28
 * @Time: 23:54
 */
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title><?php echo $title ?? ADMIN_DEFAULT_TITLE; ?></title>
    <link rel="bookmark" type="image/x-icon" href="<?php echo FAVICON_URL ?>"/>
    <link rel="shortcut icon" href="<?php echo FAVICON_URL ?>"/>
    <link rel="stylesheet" href="<?php echo STATIC_URL . '/layui/css/layui.css'; ?>"/>
    <script type="text/javascript" src="<?php echo STATIC_URL . '/js/jquery.min.js' ?>"></script>
</head>
<body>
<div class="layui-layout layui-layout-admin">
    <div class="layui-header">
        <div class="layui-logo">后台管理</div>
        <!-- 头部区域（可配合layui已有的水平导航） -->
        <ul class="layui-nav layui-layout-left">
            <?php
            if (! empty($top_category)):
                foreach ($top_category as $val):?>
                    <li class="layui-nav-item <?php if ($val['current'] === true) {
                        echo 'layui-this';
                    } ?>">
                        <a href="<?php echo $val['url'] ?>"><?php echo $val['name'] ?></a>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
        </ul>
        <ul class="layui-nav layui-layout-right">
            <li class="layui-nav-item">
                <a href="javascript:;">
                    <i class="layui-icon">&#xe612;</i>
                    <span>管理员：</span>
                    谢勇
                </a>
                <dl class="layui-nav-child">
                    <dd><a href="">个人中心</a></dd>
                    <dd><a href="">修改密码</a></dd>
                    <dd><a href="">退出</a></dd>
                </dl>
            </li>
            <li class="layui-nav-item">
                <a href="<?php echo \Library\Tools\UrlHelper::siteUrl();?>" target="_blank">浏览站点</a>
            </li>
        </ul>
    </div>

    <div class="layui-side layui-bg-black">
        <div class="layui-side-scroll">
            <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
            <ul class="layui-nav layui-nav-tree" lay-filter="test">
                <?php
                if (! empty($left_category)):
                    foreach ($left_category as $left_item): ?>
                        <li class="layui-nav-item layui-nav-itemed">
                            <a class="" href="<?php echo $left_item['url']; ?>"><?php echo $left_item['name']; ?></a>
                            <?php
                            if (! empty($left_item['child'])): ?>
                                <dl class="layui-nav-child">
                                    <?php foreach ($left_item['child'] as $child): ?>
                                        <dd><a href="<?php echo $child['url']; ?>"><?php echo $child['name'] ?></a>
                                        </dd>
                                    <?php endforeach; ?>
                                </dl>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul>
        </div>
    </div>

    <div class="layui-body">
        <!-- 内容主体区域 -->
        <div style="padding: 15px;">内容主体区域</div>
    </div>

    <div class="layui-footer">
        <!-- 底部固定区域 -->
        © layui.com - 底部固定区域
    </div>
</div>

<script type="text/javascript">
    $(function () {

    });
</script>

<!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
<!--[if lt IE 9]>
<script type="text/javascript" src="<?php echo STATIC_URL . '/js/respond.min.js' ?>"></script>
<script type="text/javascript" src="<?php echo STATIC_URL . '/js/html5.min.js' ?>"></script>
<![endif]-->
<script type="text/javascript" src="<?php echo STATIC_URL . '/layui/layui.all.js'; ?>"></script>
</body>
</html>